import { LEVELS, PERMISSIONS } from "./admin-policy";

export function policyDialogs(): string { return String.raw`
<dialog id="reasonDialog" aria-labelledby="reasonTitle"><div class="dialog-head"><h2 id="reasonTitle">填写操作原因</h2></div><div class="dialog-body"><form id="reasonForm" class="auth-form"><p id="reasonContext" class="muted"></p><label>操作原因<textarea id="operationReason" required minlength="3" maxlength="1000" placeholder="说明本次管理操作的原因，至少 3 个字"></textarea></label><div class="form-actions"><button type="button" id="reasonCancel">取消操作</button><button class="primary" type="submit">继续操作</button></div></form></div></dialog>`; }

export function policyClient(): string { return String.raw`
const levelNames=${JSON.stringify(LEVELS)}, permissionCatalog=${JSON.stringify(PERMISSIONS)};
const canUsers=()=>Boolean(state.user?.globalCapabilities?.includes('user.read'));
const capability=(p,id=state.instance)=>Boolean(state.instances.find(i=>i.id===id)?.capabilities?.includes(p));
const levelName=u=>levelNames[u?.level]||'普通成员';
let permissionRevision=0, auditCursor=null, reasonResolve=null;
let assignedSelected=new Set();
function renderAssignedPicker(){const box=$('#assignedInstances');if(!box)return;const count=$('#assignedPickerCount');const cards=state.instances.map(i=>{const own=Boolean(permissionsUserId&&i.ownerId===permissionsUserId);const chosen=own||assignedSelected.has(i.id);const ownerLabel=own?'该用户自己的实例':(i.ownerId?'用户 #'+i.ownerId:'服务器所有');return '<button type="button" class="instance-option'+(chosen?' selected':'')+(own?' own':'')+'" data-assigned="'+esc(i.id)+'" '+(own?'disabled aria-disabled="true" title="该用户自己的实例，默认保留"':'')+' aria-pressed="'+chosen+'" aria-label="'+(own?'该用户自己的实例（固定勾选）':(chosen?'取消选择':'选择'))+'实例 '+esc(i.name)+'"><span class="opt-head"><strong>'+esc(i.name)+'</strong><span class="pick-check" aria-hidden="true"></span></span><span class="opt-id">#'+esc(i.id)+'</span><span class="opt-meta">'+esc(ownerLabel)+' · '+(i.enabled?'已启用':'已停用')+'</span><span class="opt-stats">'+number(i.chartCount||0)+' 张谱面 · '+number(i.recordCount||0)+' 条成绩</span></button>'}).join('');box.innerHTML=cards||'<div class="help" style="grid-column:1/-1;padding:12px 2px">没有可选择的实例</div>';if(count){const ownCount=state.instances.filter(i=>permissionsUserId&&i.ownerId===permissionsUserId).length;const n=assignedSelected.size+ownCount;count.textContent=n?('已选 '+n+' 个'):'未选择';count.className='badge'+(n?' green':'')}}
function toggleAssigned(id){if(!id||!state.instances.some(i=>i.id===id))return;if(permissionsUserId&&state.instances.some(i=>i.id===id&&i.ownerId===permissionsUserId))return;if(assignedSelected.has(id))assignedSelected.delete(id);else assignedSelected.add(id);renderAssignedPicker()}
function clearPolicyCache(){auditCursor=null;$('#auditEvents').replaceChildren();$('#auditMore').hidden=true;if(state.user?.role!=='admin'){$('#permissionsDialog').close();$('#grantRows').replaceChildren();assignedSelected.clear();renderAssignedPicker();$('#permissionReason').value='';permissionsUserId=null}if(!canReview()){$('#reviewApplication').replaceChildren();$('#reviewHistory').replaceChildren()}}
function askReason(context){return new Promise(resolve=>{reasonResolve=resolve;$('#reasonContext').textContent=context;$('#operationReason').value='';$('#reasonDialog').showModal();$('#operationReason').focus()})}
function finishReason(value){$('#reasonDialog').close();const resolve=reasonResolve;reasonResolve=null;resolve?.(value)}
$('#reasonForm').onsubmit=e=>{e.preventDefault();finishReason($('#operationReason').value.trim())};$('#reasonCancel').onclick=()=>finishReason(null);$('#reasonDialog').addEventListener('cancel',e=>{e.preventDefault();finishReason(null)});
async function policyRequest(path,options){
  const method=options.method||'GET';if(['GET','HEAD'].includes(method)||path.startsWith('/api/admin/auth/'))return options;
  const data=typeof options.body==='string'?JSON.parse(options.body):null;
  const instanceId=path.startsWith('/api/admin/instances/')?path.split('/')[4]:state.instance;
  const instance=state.instances.find(i=>i.id===instanceId);
  const userMutation=/^\/api\/admin\/users\/\d+(?:\/logout)?$/.test(path);
  const roomMutation=path.startsWith('/api/admin/rooms');
  const risky=method==='DELETE'||path.includes('batch-delete')||path.startsWith('/api/admin/records')||path.startsWith('/api/admin/instances/')&&data&&('visibility'in data||'enabled'in data)||/^\/api\/admin\/charts\/-?\d+$/.test(path)&&data&&'listed'in data;
  let reason=data?.reason;
  // Room controls are already scoped by the server to the current website owner.
  // Keep an audit reason without interrupting every create/edit/chat/disband action.
  if(!reason&&roomMutation)reason='网页多人房间操作';
  if(!reason&&(userMutation||risky&&instance&&instance.ownerId!==state.user?.id)){
    reason=await askReason(userMutation?'此操作会改变其他账号的状态或配额，并写入操作记录。':'正在管理实例「'+instance.name+'」。操作原因会写入审计记录。');
    if(reason===null)throw new Error('操作已取消');
  }
  const headers={...options.headers};if(reason)headers['X-Admin-Reason']=encodeURIComponent(reason);
  if(path.startsWith('/api/admin/instances/')&&method==='DELETE')headers['X-Admin-Confirm']=instanceId;
  if(path.includes('/charts/batch-delete'))headers['X-Admin-Confirm']='delete';
  if(userMutation&&method==='DELETE')headers['X-Admin-Confirm']='delete';
  if(userMutation&&data)options={...options,body:JSON.stringify({...data,reason})};
  return {...options,headers};
}
function renderPolicyControls(){
  for(const [selector,p] of [['#uploadSubmit','chart.upload'],['#addRecord','record.create'],['#deleteByTag','chart.purge'],['#deleteAll','chart.purge'],['#deleteSelected','chart.purge'],['#batchTags','chart.tags'],['[data-action=download]','chart.download'],['[data-action=preview]','chart.read'],['[data-action=edit]','chart.edit'],['[data-action=delete]','chart.delete'],['#roomsReload','monitor.view'],['[data-action=delete-record]','record.delete']])$$(selector).forEach(b=>b.disabled=state.busy||!state.ready||!capability(p));
  $$('[data-action=visibility]').forEach(b=>{const c=state.charts.find(c=>c.id===Number(b.dataset.id));b.disabled=state.busy||!capability(c?.listed===false?'chart.publish':'chart.hide')});
  $$('[data-action=delete-instance]').forEach(b=>b.disabled=state.busy||!capability('instance.delete',b.dataset.instance));
  $$('[data-action=edit-instance]').forEach(b=>b.disabled=state.busy||!['instance.rename','instance.visibility','instance.enable','instance.disable'].some(p=>capability(p,b.dataset.instance)));
  for(const [view,p] of [['upload','chart.upload'],['records','record.read']])$('[data-view='+view+']').hidden=Boolean(awaitingApproval())||!capability(p);
  if($('#myPermissions')){
    const u=state.user;$('#myPermissions').textContent=u?levelName(u)+' · 实例配额 '+(u.role==='admin'?'不限':u.instanceLimit)+'。当前实例可操作：'+(state.instances.find(i=>i.id===state.instance)?.capabilities||[]).map(p=>permissionCatalog.find(x=>x[0]===p)?.[1]||p).join('、'):'请先登录';
    $('#myExtraGrants').textContent=(u?.grants||[]).map(g=>(g.effect==='deny'?'禁止':'允许')+' '+(permissionCatalog.find(p=>p[0]===g.permission)?.[1]||g.permission)+' · '+(g.scope==='selected'?g.instanceIds.join(', '):g.scope==='own'?'自己':'全部')+' · '+(g.expiresAt?(Date.parse(g.expiresAt)<=Date.now()?'已过期 ':'到期 ')+formatTime(g.expiresAt):'长期')).join('\n')||'没有额外授权';
  }
}
function prepareInstancePolicy(id){const isNew=!id;const i=state.instances.find(i=>i.id===id);
  $('#instanceName').disabled=!isNew&&!capability('instance.rename',id);
  $('#instanceVisibility').disabled=!isNew&&!capability('instance.visibility',id);$('#instanceViewers').disabled=$('#instanceVisibility').value!=='users'||$('#instanceVisibility').disabled;
  $('#instanceEnabled').disabled=!isNew&&!capability(i?.enabled?'instance.disable':'instance.enable',id);
}
function permissionInstanceOptions(selected=[]){return state.instances.map(i=>'<option value="'+esc(i.id)+'" '+(selected.includes(i.id)?'selected':'')+'>'+esc(i.name)+' · '+esc(i.id)+'</option>').join('')}
function addGrantRow(g={permission:'instance.read',effect:'allow',scope:'selected',instanceIds:[],expiresAt:null}){
  const row=document.createElement('div');row.className='panel panel-body grant-row';row.style.marginBottom='12px';
  const choices=permissionCatalog.filter(p=>$('#memberLevel').value==='manager'||!(/^(user|application|review)\./.test(p[0])));
  row.innerHTML='<div class="form-grid"><label>操作及风险<select data-grant-permission>'+choices.map(p=>'<option value="'+p[0]+'">'+esc(p[1])+' · '+p[2]+'风险</option>').join('')+'</select></label><label>授权方式<select data-grant-effect><option value="allow">额外允许</option><option value="deny">禁止默认权限</option></select></label><label>作用范围<select data-grant-scope><option value="selected">指定实例</option><option value="all">全部适用对象</option></select></label><label>到期时间（可留空）<input data-grant-expiry type="datetime-local"></label><label class="full" data-grant-instances-label>选择实例（可多选）<select multiple size="4" data-grant-instances>'+permissionInstanceOptions(g.instanceIds)+'</select></label></div><button type="button" class="small ghost danger" data-remove-grant style="margin-top:12px">移除此授权</button>';
  row.querySelector('[data-grant-permission]').value=g.permission;row.querySelector('[data-grant-effect]').value=g.effect;row.querySelector('[data-grant-scope]').value=g.scope==='own'?'selected':g.scope;
  if(g.expiresAt){const d=new Date(g.expiresAt);row.querySelector('[data-grant-expiry]').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
  const sync=()=>{const global=/^(user|application|review)\./.test(row.querySelector('[data-grant-permission]').value);const scope=row.querySelector('[data-grant-scope]');if(global)scope.value='all';scope.disabled=global;row.querySelector('[data-grant-instances-label]').hidden=scope.value!=='selected'};
  row.querySelector('[data-grant-permission]').onchange=sync;row.querySelector('[data-grant-scope]').onchange=sync;row.querySelector('[data-remove-grant]').onclick=()=>row.remove();sync();$('#grantRows').append(row);
}
function openPermissions(id){if(state.busy||state.user?.role!=='admin')return;const user=state.users.find(u=>u.id===id);permissionsUserId=id;permissionRevision=user.permissionRevision;$('#permissionsTitle').textContent='等级与权限 · '+user.username;$('#memberLevel').value=user.level;assignedSelected=new Set(user.assignedInstances||[]);renderAssignedPicker();$('#permissionReason').value='';$('#grantResetNote').textContent='';$('#grantRows').replaceChildren();(user.grants||[]).forEach(addGrantRow);renderLevelHelp();$('#permissionsDialog').showModal()}
function renderLevelHelp(){const value=$('#memberLevel').value;$('#levelHelp').textContent={ordinary:'管理自己的实例，不具备平台管理权限。',advanced:'协助维护下方指定实例的谱面，可以查看成绩；不能审核注册。',senior:'负责指定实例的内容维护；可由超级管理员另行授予启停等权限。不能查看或审核注册申请。',manager:'审核注册，管理普通、进阶、高级成员的账号与实例。不能管理同级管理员或超级管理员，不能提权或改配额。'}[value];$('#assignedField').hidden=!['advanced','senior'].includes(value)}
$('#memberLevel').onchange=()=>{$('#grantRows').replaceChildren();assignedSelected.clear();renderAssignedPicker();renderLevelHelp();$('#grantResetNote').textContent='等级已变更，原协作范围和额外授权已清空。需要保留的权限请重新添加。'};
$('#addGrant').onclick=()=>addGrantRow();
$('#permissionsForm').onsubmit=e=>{e.preventDefault();const grants=$$('.grant-row').map(row=>({permission:row.querySelector('[data-grant-permission]').value,effect:row.querySelector('[data-grant-effect]').value,scope:row.querySelector('[data-grant-scope]').value,instanceIds:Array.from(row.querySelector('[data-grant-instances]').selectedOptions).map(o=>o.value),expiresAt:row.querySelector('[data-grant-expiry]').value?new Date(row.querySelector('[data-grant-expiry]').value).toISOString():null}));task(e.submitter,async()=>{await api('/api/admin/users/'+permissionsUserId+'/permissions',jsonOptions('PATCH',{level:$('#memberLevel').value,assignedInstances:[...assignedSelected],grants,revision:permissionRevision,reason:$('#permissionReason').value.trim()}));$('#permissionsDialog').close();toast('等级与授权已保存，立即生效；实例配额保持不变');await refresh()})};
$('#assignedInstances').addEventListener('click',e=>{const card=e.target.closest('[data-assigned]');if(card)toggleAssigned(card.dataset.assigned)});
function renderUsers(){const q=$('#userSearch').value.trim().toLowerCase(),filter=$('#approvalFilter').value,superAdmin=state.user?.role==='admin';$('#users').innerHTML=state.users.filter(u=>(!q||String(u.id).includes(q)||u.username.includes(q))&&(!filter||u.approvalStatus===filter)).sort((a,b)=>(a.approvalStatus==='pending'?-1:0)-(b.approvalStatus==='pending'?-1:0)||a.id-b.id).map(u=>{
  const manageable=u.role!=='admin'&&u.id!==state.user.id&&(superAdmin||u.level!=='manager');
  return '<tr><td>'+esc(u.username)+'<div class="chart-sub">#'+u.id+'</div></td><td>'+esc(levelName(u))+(superAdmin&&u.grants?.length?'<div class="chart-sub">'+u.grants.length+' 条额外规则</div>':'')+'</td><td>'+u.instanceCount+'</td><td>'+(u.role==='admin'?'不限':superAdmin?'<input class="user-quota" data-quota="'+u.id+'" aria-label="'+esc(u.username)+' 的实例配额" type="number" min="0" max="10000" step="1" value="'+u.instanceLimit+'">':u.instanceLimit)+'</td><td><span class="badge '+(u.disabled?'rejected':u.approvalStatus==='approved'?'green':u.approvalStatus)+'">'+(u.disabled?'已停用':statusLabel(u.approvalStatus))+'</span></td><td><div class="row-actions">'+(canReview()&&manageable?'<button class="small" data-review-user="'+u.id+'">'+(u.approvalStatus==='pending'?'审核申请':'申请资料')+'</button>':'')+(superAdmin&&u.role!=='admin'?'<button class="small" data-save-user="'+u.id+'">保存配额</button><button class="small" data-permissions-user="'+u.id+'">等级与权限</button>':'')+(manageable&&state.user.globalCapabilities.includes(u.disabled?'user.restore':'user.suspend')?'<button class="small danger" data-disable-user="'+u.id+'">'+(u.disabled?'恢复账号':'停用账号')+'</button>':'')+(manageable&&state.user.globalCapabilities.includes('user.logout')?'<button class="small ghost" data-logout-user="'+u.id+'">强制退出</button>':'')+(superAdmin&&u.role!=='admin'&&u.id!==state.user.id?'<button class="small danger" data-delete-user="'+u.id+'">删除账号</button>':'')+'</div></td></tr>';
}).join('')||emptyRow(6,'暂无匹配用户','注册申请仅管理员和超级管理员可访问。')}
$('#users').onclick=e=>{const review=e.target.closest('[data-review-user]'),permissions=e.target.closest('[data-permissions-user]'),save=e.target.closest('[data-save-user]'),disable=e.target.closest('[data-disable-user]'),logout=e.target.closest('[data-logout-user]'),deleteUser=e.target.closest('[data-delete-user]');if(review)task(review,()=>openReview(Number(review.dataset.reviewUser)));if(permissions)openPermissions(Number(permissions.dataset.permissionsUser));if(save)task(save,async()=>{const id=Number(save.dataset.saveUser),input=$('[data-quota="'+id+'"]');if(!input.reportValidity())return;await api('/api/admin/users/'+id,jsonOptions('PATCH',{instanceLimit:Number(input.value)}));toast('配额已保存');await refresh()});if(disable)task(disable,async()=>{const user=state.users.find(u=>u.id===Number(disable.dataset.disableUser));await api('/api/admin/users/'+user.id,jsonOptions('PATCH',{disabled:!user.disabled}));toast('账号状态已更新');await refresh()});if(logout)task(logout,async()=>{await api('/api/admin/users/'+logout.dataset.logoutUser+'/logout',jsonOptions('POST',{}));toast('该用户的登录会话已撤销');await refresh()});if(deleteUser){const user=state.users.find(u=>u.id===Number(deleteUser.dataset.deleteUser));confirmDelete('删除账号「'+user.username+'」','账号、登录会话与权限将被永久删除。该账号拥有的 '+user.instanceCount+' 个实例和其中的数据不会删除，将转为服务器所有。',async()=>{const result=await api('/api/admin/users/'+user.id,{method:'DELETE'});$('#confirmDialog').close();toast('账号已删除，保留 '+result.instancesPreserved.length+' 个实例');await refresh()})}};
async function loadAudit(append=false){const data=await api('/api/admin/audit'+(append&&auditCursor?'?before='+auditCursor:''));if(!append)$('#auditEvents').replaceChildren();for(const event of data.events){const box=document.createElement('details');box.className='panel panel-body';const summary=document.createElement('summary');summary.textContent=formatTime(event.created)+' · #'+event.actorId+' · '+event.action+' · '+event.outcome;const reason=document.createElement('p');reason.className='help';reason.textContent=(event.instanceId?'实例 '+event.instanceId+' · ':'')+(event.reason||'常规操作');const changes=document.createElement('pre');changes.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px';changes.textContent=JSON.stringify({修改前:event.before,修改后:event.after},null,2);box.append(summary,reason,changes);$('#auditEvents').append(box)}auditCursor=data.nextCursor;$('#auditMore').hidden=!auditCursor;if(!$('#auditEvents').children.length)$('#auditEvents').textContent='暂无权限范围内的操作记录'}
$('#auditReload').onclick=e=>task(e.currentTarget,()=>loadAudit());$('#auditMore').onclick=e=>task(e.currentTarget,()=>loadAudit(true));
`; }
