export function adminAuthMarkup(): string {
  return String.raw`<section id="authGate" class="auth-gate"><div class="auth-card"><h1>Phira 本地谱面管理系统</h1>
<div class="auth-tabs"><button id="showLogin" class="primary">登录</button><button id="showRegister" class="ghost">注册账号</button></div>
<form id="loginForm" class="auth-form"><label>用户名<input name="username" autocomplete="username" required maxlength="32"></label><label>密码<input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><button class="primary" type="submit">登录管理面板</button></form>
<form id="registerForm" class="auth-form" hidden><label>用户名<input name="username" autocomplete="username" required pattern="[a-z0-9][a-z0-9_-]{2,31}" maxlength="32" placeholder="3–32 位小写字母、数字、_ 或 -"></label><label>密码<input name="password" type="password" autocomplete="new-password" required minlength="10" maxlength="128" placeholder="至少 10 个字符"></label><label>确认密码<input name="confirmPassword" type="password" autocomplete="new-password" required minlength="10" maxlength="128"></label><label>注册原因 / 计划如何使用<textarea name="reason" required minlength="10" maxlength="2000" placeholder="请具体描述使用计划，至少 10 个字符"></textarea></label><label>用途类型<select name="useType"><option value="personal">个人用途</option><option value="group">团体用途</option></select></label><label data-organization hidden>团体名称<input name="organization" minlength="2" maxlength="120" placeholder="社团、团队或社区名称"></label><label>社交平台及账号<textarea name="socialAccount" required minlength="2" maxlength="500" placeholder="例如 Bilibili：账号名；QQ：账号；也可填写主页链接"></textarea></label><label>补充说明（可选）<textarea name="notes" maxlength="1000" placeholder="可补充团体介绍、预计使用人数或相关作品"></textarea></label><p class="help">申请资料仅供你和有审核权限的管理员查看。审核通过后默认可创建 2 个实例。</p><button class="primary" type="submit">提交注册申请</button></form>
<details id="setupDetails" class="details" hidden><summary>服务器所有者：初始化超级管理员</summary><form id="setupForm" class="auth-form"><label>现有管理令牌<input name="adminToken" type="password" autocomplete="off" required></label><label>管理员用户名<input name="username" autocomplete="username" required pattern="[a-z0-9][a-z0-9_-]{2,31}" maxlength="32"></label><label>密码<input name="password" type="password" autocomplete="new-password" minlength="10" maxlength="128" required></label><label>确认密码<input name="confirmPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required></label><p class="help">必须使用服务器已有管理令牌验证身份。普通注册不会获得管理员权限。</p><button class="primary" type="submit">创建超级管理员</button></form></details>
<p id="authError" class="callout error" role="alert" hidden style="margin-top:20px"></p></div></section>
`;
}
