import { policyClient } from "./admin-policy-ui";
import { previewClient } from "./admin-preview-ui";
export function adminClient(): string {
  return String.raw`
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const TOKEN_KEY='private-gateway-admin-token', INSTANCE_KEY='private-gateway-instance';
const storage={get(store,key){try{return window[store].getItem(key)||''}catch{return ''}},set(store,key,value){try{value?window[store].setItem(key,value):window[store].removeItem(key)}catch{}}};
const state={instance:storage.get('localStorage',INSTANCE_KEY)||'default',instances:[],charts:[],records:[],managedRooms:[],selected:new Set(),chartPage:1,recordPage:1,view:'charts',busy:false,ready:false,user:null,csrf:'',users:[]};
const initialView=location.hash.slice(1);
const titles={audit:'操作记录',charts:'谱面库',upload:'上传谱面',records:'本地成绩',instances:'服务实例',rooms:'房间',settings:'连接与设置',users:'用户与审核',application:'申请状态',docs:'使用文档'};
let editId=null,instanceEditId=null,confirmCallback=null,reviewUserId=null,reviewRevision=0,permissionsUserId=null;
const canReview=()=>Boolean(state.user?.globalCapabilities?.includes('application.read'));
const canManageInstances=()=>state.user?.role==='admin'||Boolean(state.user?.permissions?.manageInstances);
const canManageRooms=()=>state.user?.role==='admin'||state.user?.level==='senior'||state.user?.level==='manager';
const awaitingApproval=()=>state.user&&state.user.approvalStatus!=='approved';
const statusLabel=s=>({pending:'待审核',approved:'已通过',rejected:'已拒绝'}[s]||'已通过');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>Number(v||0).toLocaleString('zh-CN');
const tags=v=>[...new Set(v.split(/[,，]/).map(s=>s.trim()).filter(Boolean))];
const currentName=()=>state.instances.find(i=>i.id===state.instance)?.name||state.instance;
const chartName=id=>state.charts.find(c=>c.id===id)?.name||('#'+id);
function toast(message,error=false){const box=document.createElement('div');box.className='toast'+(error?' error':'');const label=document.createElement('span');label.textContent=message;const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','关闭通知');close.onclick=()=>box.remove();box.append(label,close);$('#toasts').append(box);if(!error)setTimeout(()=>box.remove(),6500);while($('#toasts').children.length>4)$('#toasts').firstChild.remove()}
function closeNavigation(){const shell=$('#workspace');shell.classList.remove('nav-open');$('#sidebarScrim').hidden=true;$('#navToggle').setAttribute('aria-expanded','false')}
function showView(view){if(!titles[view])view='charts';if(state.user){if(view==='users'&&!canUsers())view='charts';if(view==='rooms'&&!capability('monitor.view'))view='charts';if(view==='upload'&&!capability('chart.upload'))view='charts';if(view==='records'&&!capability('record.read'))view='charts';if(view==='audit'&&!capability('audit.read'))view='charts';if(['charts','upload','records'].includes(view)&&!state.instances.length)view='instances';if(awaitingApproval()&&!['application','settings','docs'].includes(view))view='application'}state.view=view;$$('[data-page]').forEach(el=>el.hidden=el.dataset.page!==view);$$('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);el.dataset.view===view?el.setAttribute('aria-current','page'):el.removeAttribute('aria-current')});$('#crumb').textContent=titles[view];history.replaceState(null,'','#'+view);closeNavigation();if(view==='rooms')renderRooms(false)}
function setConnected(ready){state.ready=ready;$('#statusDot').classList.toggle('online',ready);$('#connectionState').textContent=ready?'管理连接正常':'尚未连接';$('#connectionButton').textContent=ready?'已连接 · 设置':'连接设置';syncControls()}
function syncControls(){for(const id of ['instanceSelect','reload','uploadSubmit','createInstance','addRecord','deleteByTag','deleteAll'])$('#'+id).disabled=state.busy||(!state.ready&&!['reload'].includes(id));$('#chartHeaderCheck').disabled=state.busy||!state.ready;$$('[data-close]').forEach(el=>el.disabled=state.busy);$('#instanceSelect').disabled=state.busy||!state.instances.length;const quotaReached=state.user?.role==='user'&&state.instances.filter(i=>i.ownerId===state.user.id).length>=state.user.instanceLimit;$('#createInstance').disabled=state.busy||!state.ready||quotaReached||Boolean(awaitingApproval());$('#createInstance').title=quotaReached?'已达到实例配额，请联系管理员':'';for(const id of ['uploadSubmit','addRecord','deleteByTag','deleteAll'])$('#'+id).disabled=state.busy||!state.ready||!state.instances.length;renderPolicyControls()}
async function task(button,action){if(state.busy)return;state.busy=true;const label=button?.textContent;if(button){button.disabled=true;button.textContent='处理中…'}syncControls();try{await action()}catch(error){toast(error.message||'操作失败，请重试',true)}finally{state.busy=false;if(button){button.disabled=false;button.textContent=label}syncControls()}}
function scopedPath(path,instance=state.instance){const url=new URL(path,location.origin);if(!url.pathname.startsWith('/api/admin/instances'))url.searchParams.set('instance',instance);return url.pathname+url.search}
async function api(path,options={}){options=await policyRequest(path,options);const token=$('#token').value.trim();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),options.body instanceof FormData?600000:30000);try{const response=await fetch(scopedPath(path),{...options,cache:'no-store',signal:controller.signal,credentials:'same-origin',headers:{'X-Admin-Request':'1',...(token?{Authorization:'Bearer '+token}:{}),...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...options.headers}});let data;try{data=await response.json()}catch{throw new Error('服务返回了无法识别的响应（HTTP '+response.status+'）')}if(!response.ok){if(response.status===401||response.status===403){if(response.status===401&&state.user)clearSession();throw new Error(data.error||'登录已过期，请重新登录')}throw new Error(data.error||('请求失败（HTTP '+response.status+'）'))}return data}catch(error){if(error.name==='AbortError')throw new Error('请求超时，结果可能已保存，请刷新确认后再重试');if(error instanceof TypeError)throw new Error('无法连接管理服务，请检查服务状态后重试');throw error}finally{clearTimeout(timer)}}
const jsonOptions=(method,body)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function fillSelect(id,items,placeholder){const el=$(id),old=el.value;el.innerHTML=(placeholder!==null?'<option value="">'+esc(placeholder)+'</option>':'')+items.map(i=>'<option value="'+esc(i.value)+'">'+esc(i.label)+'</option>').join('');if(Array.from(el.options).some(i=>i.value===old))el.value=old}
function resetFilters(){$('#chartSearch').value='';$('#visibilityFilter').value='';$('#tagFilter').value='';$('#recordSearch').value='';$('#recordChart').value='';state.chartPage=state.recordPage=1;state.selected.clear();$('#uploadResult').hidden=true}
async function refresh(){clearPolicyCache();try{if(state.user&&!$('#token').value){const me=await api('/api/admin/auth/me');state.user=me.user;state.csrf=me.csrf}if(awaitingApproval()){state.instances=[];state.charts=[];state.records=[];state.users=[];state.selected.clear();setConnected(true);$('#loadError').hidden=true;render();showView('application');return}const instances=await api('/api/admin/instances');state.instances=instances;if(!instances.some(i=>i.id===state.instance)){state.instance=instances[0]?.id||'default';resetFilters()}const requestedInstance=state.instance;const data=instances.length?await api('/api/admin/dashboard'):{charts:[],records:[]};if(canUsers())state.users=await api('/api/admin/users');else state.users=[];if(requestedInstance!==state.instance)return;state.charts=data.charts||[];state.records=data.records||[];state.selected=new Set([...state.selected].filter(id=>state.charts.some(c=>c.id===id)));storage.set('localStorage',INSTANCE_KEY,state.instance);setConnected(true);$('#loadError').hidden=true;render();$('#lastUpdated').textContent='更新于 '+new Date().toLocaleTimeString('zh-CN',{hour12:false})}catch(error){setConnected(false);state.charts=[];state.records=[];state.selected.clear();render();$('#loadError').textContent='加载失败：'+error.message;$('#loadError').hidden=false;throw error}}
function render(){renderAccount();fillSelect('#instanceSelect',state.instances.map(i=>({value:i.id,label:i.name+' · '+i.id})),null);$('#instanceSelect').value=state.instance;$('#sideInstance').textContent=currentName();$('#uploadInstance').textContent=currentName();$('#cleanupInstance').textContent=currentName();$('#statCharts').textContent=state.ready?number(state.charts.length):'—';$('#statListed').textContent=state.ready?number(state.charts.filter(c=>c.listed!==false).length):'—';$('#statRecords').textContent=state.ready?number(state.records.length):'—';$('#statPlayers').textContent=state.ready?number(new Set(state.records.map(r=>r.player)).size):'—';$('#navCount').textContent=state.ready?number(state.charts.length):'—';const allTags=[...new Set(state.charts.flatMap(c=>c.tags||[]))].sort((a,b)=>a.localeCompare(b,'zh-CN'));fillSelect('#tagFilter',allTags.map(t=>({value:t,label:t})),'全部标签');fillSelect('#deleteTag',allTags.map(t=>({value:t,label:t})),'选择标签');const charts=state.charts.map(c=>({value:String(c.id),label:c.name+' (#'+c.id+')'}));fillSelect('#recordChart',charts,'全部谱面');fillSelect('#recordFormChart',charts,'请选择谱面');$('#roomChartOptions').innerHTML=state.charts.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');renderCharts();renderRecords();renderInstances();renderUsers();renderApplication();syncControls();if(state.user)showView(state.view)}
function filteredCharts(){const q=$('#chartSearch').value.trim().toLocaleLowerCase(),tag=$('#tagFilter').value,visible=$('#visibilityFilter').value;const list=state.charts.filter(c=>(!q||[c.id,c.name,c.charter,c.composer,...(c.tags||[])].join(' ').toLocaleLowerCase().includes(q))&&(!tag||(c.tags||[]).includes(tag))&&(!visible||(c.listed!==false)===(visible==='listed')));const sort=$('#chartSort').value;return list.sort((a,b)=>sort==='name'?String(a.name).localeCompare(String(b.name),'zh-CN'):sort==='id'?a.id-b.id:sort==='difficulty'?b.difficulty-a.difficulty:String(b.created||'').localeCompare(String(a.created||''))||b.id-a.id)}
function emptyRow(columns,title,description){return '<tr><td colspan="'+columns+'" class="empty"><strong>'+esc(title)+'</strong><small>'+esc(description)+'</small></td></tr>'}
function pageItems(list,type){const key=type+'Page',pages=Math.max(1,Math.ceil(list.length/20));state[key]=Math.max(1,Math.min(state[key],pages));const offset=(state[key]-1)*20;$('#'+type+'Page').textContent=state[key]+' / '+pages;$('#'+type+'Prev').disabled=state[key]<=1;$('#'+type+'Next').disabled=state[key]>=pages;$('#'+type+'Range').textContent=list.length?'第 '+(offset+1)+'–'+Math.min(offset+20,list.length)+' 条，共 '+number(list.length)+' 条':'共 0 条';return list.slice(offset,offset+20)}
function renderCharts(){const list=filteredCharts(),page=pageItems(list,'chart');$('#chartCount').textContent='· '+number(state.charts.length);$('#charts').innerHTML=page.map(c=>'<tr class="'+(state.selected.has(c.id)?'selected':'')+'"><td><input class="chart-check" type="checkbox" value="'+c.id+'" aria-label="选择 '+esc(c.name)+'" '+(state.selected.has(c.id)?'checked':'')+'></td><td><div class="chart-name" title="'+esc(c.name)+'">'+esc(c.name)+'</div><div class="chart-sub">'+esc(c.charter||c.composer||'未填写作者')+'</div></td><td class="mono">#'+c.id+'</td><td><span class="badge level">'+esc(c.level||'Custom')+'</span></td><td class="tags">'+((c.tags||[]).map(t=>'<span class="badge">'+esc(t)+'</span>').join('')||'<span class="muted">—</span>')+'</td><td><button class="switch '+(c.listed!==false?'on':'')+'" data-action="visibility" data-id="'+c.id+'" aria-pressed="'+(c.listed!==false)+'" aria-label="切换 '+esc(c.name)+' 的在线显示">'+(c.listed!==false?'● 显示中':'○ 已隐藏')+'</button></td><td><div class="row-actions"><button class="small ghost" data-action="preview" data-id="'+c.id+'">预览</button><button class="small" data-action="edit" data-id="'+c.id+'">编辑</button><button class="small ghost" data-action="download" data-id="'+c.id+'">下载</button><button class="small ghost danger" data-action="delete" data-id="'+c.id+'">删除</button></div></td></tr>').join('')||emptyRow(7,state.ready?(state.charts.length?'没有匹配的谱面':'还没有谱面'):'连接后查看谱面',state.ready?(state.charts.length?'试试其他关键词，或调整标签与状态筛选。':'点击「上传谱面」，导入你的第一个谱面包。'):'在连接设置中输入管理令牌。');$$('#charts .chart-check').forEach(input=>{const hit=document.createElement('label');hit.className='check-hit';input.before(hit);hit.append(input)});const checked=page.filter(c=>state.selected.has(c.id)).length;$('#chartHeaderCheck').checked=page.length>0&&checked===page.length;$('#chartHeaderCheck').indeterminate=checked>0&&checked<page.length;$('#batchBar').hidden=!state.selected.size;$('#selectedCount').textContent='已选择 '+state.selected.size+' 张 · 当前实例（包含其他页）'}
function renderRecords(){const q=$('#recordSearch').value.trim().toLocaleLowerCase(),chart=$('#recordChart').value,sort=$('#recordSort').value;const list=state.records.filter(r=>(!chart||String(r.chart)===chart)&&(!q||[r.id,r.player,r.chart,chartName(r.chart)].join(' ').toLocaleLowerCase().includes(q))).sort((a,b)=>sort==='score'?b.score-a.score:sort==='accuracy'?b.accuracy-a.accuracy:String(b.time).localeCompare(String(a.time)));$('#recordCount').textContent='· '+number(state.records.length);$('#records').innerHTML=pageItems(list,'record').map(r=>'<tr><td><div class="mono">'+r.player+'</div><div class="chart-sub">记录 #'+r.id+'</div></td><td><div class="chart-name">'+esc(chartName(r.chart))+'</div><div class="chart-sub">#'+r.chart+'</div></td><td>'+number(r.score)+'</td><td class="mono">'+(Number(r.accuracy)*100).toFixed(2)+'%</td><td>'+(r.best?'<span class="badge green">BEST</span>':'')+(r.full_combo||r.fullCombo?'<span class="badge level">FC</span>':'')+(!r.best&&!r.full_combo&&!r.fullCombo?'<span class="muted">—</span>':'')+'</td><td class="mono">'+esc(formatTime(r.time))+'</td><td><button class="small ghost danger" data-action="delete-record" data-id="'+r.id+'">删除</button></td></tr>').join('')||emptyRow(7,state.records.length?'没有匹配的成绩':'暂无成绩记录',state.records.length?'调整搜索词或谱面筛选。':'玩家完成演奏并成功上传后，成绩会显示在这里。')}
function formatTime(value){const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('zh-CN',{hour12:false})}
function audienceLabel(i){return !i.visibility?"保留原有入口显示":i.visibility.mode==="all"?"所有人可见":i.visibility.mode==="users"?"指定 "+i.visibility.userIds.length+" 位用户可见":"所有人不可见"}
function syncAudience(){const targeted=$("#instanceVisibility").value==="users";$("#instanceViewerField").hidden=!targeted;$("#instanceViewers").disabled=!targeted;$("#instanceViewers").required=targeted}
$("#instanceVisibility").onchange=syncAudience;
function renderInstances(){$('#instanceCards').innerHTML=state.instances.map(i=>'<article class="instance-card '+(i.id===state.instance?'current':'')+'"><h3>'+esc(i.name)+(i.id===state.instance?'<span class="badge green">当前</span>':'')+'</h3><span class="mono">'+esc(i.id)+'</span><span class="badge '+(i.enabled?'green':'')+'" style="margin-left:10px">'+(i.enabled?'已启用':'已停用')+'</span><p><span class="badge">'+esc(audienceLabel(i))+'</span>'+(i.listingEnabled===false?' <span class="muted">在线列表总开关已关闭</span>':'')+'</p><div class="hosts">'+esc(state.user?.role==='admin'?((i.hosts||[]).join(' · ')||'未绑定域名'):'独立谱面与成绩空间')+'</div><span class="instance-owner">'+esc(i.ownerId?(state.users.find(u=>u.id===i.ownerId)?.username||'用户 #'+i.ownerId):'服务器所有者')+'</span><small>'+number(i.chartCount)+' 张谱面 &nbsp; / &nbsp; '+number(i.recordCount)+' 条成绩</small><div class="row-actions"><button class="small" data-action="switch-instance" data-instance="'+esc(i.id)+'" '+(i.id===state.instance?'disabled':'')+'>进入实例</button><button class="small ghost" data-action="edit-instance" data-instance="'+esc(i.id)+'">设置</button>'+(i.id!=='default'?'<button class="small ghost danger" data-action="delete-instance" data-instance="'+esc(i.id)+'">删除</button>':'')+'</div></article>').join('')||'<div class="panel panel-body muted">连接后查看服务实例。</div>'}
async function switchInstance(id){if(id===state.instance)return;state.instance=id;resetFilters();await refresh();toast('已切换到「'+currentName()+'」')}
const ROOM_STATE={select_chart:'选曲中',selecting_chart:'选曲中',selectchart:'选曲中',waiting_for_ready:'准备中',waitforready:'准备中',playing:'演奏中',completed:'已完成'};
let roomEditId=null,roomRefreshTimer=null;
const roomStateLabel=value=>ROOM_STATE[String(value||'').replace(/[^a-z]/gi,'').toLowerCase()]||ROOM_STATE[String(value||'').toLowerCase()]||value||'—';
async function renderRooms(force){
  const body=$('#rooms'),box=$('#roomsStatus');
  if(!body||!box)return;
  if(roomRefreshTimer){clearTimeout(roomRefreshTimer);roomRefreshTimer=null}
  try{
    const data=await api('/api/admin/monitor/rooms'+(force?'?refresh=1':''));
    let managed=[],managedError='';
    if(canManageRooms())try{const result=await api('/api/admin/rooms');managed=result.rooms||[];state.managedRooms=managed}catch(error){managedError=error.message||String(error);state.managedRooms=[]}
    else state.managedRooms=[];
    const status=data.status||{},monitorRooms=data.rooms||[],notes=[],managedById=new Map(managed.map(room=>[room.roomid,room]));
    const rooms=monitorRooms.map(room=>({...room,managed:managedById.get(room.id)||null}));
    for(const room of managed)if(!rooms.some(item=>item.id===room.roomid))rooms.push({id:room.roomid,chartId:room.chart?.id??null,chartName:room.chart?.name??null,state:room.state||null,playerCount:(room.users||[]).length,maxUsers:room.capacity,locked:false,lastScore:null,instanceId:room.instanceId||null,managed:room});
    notes.push(status.enabled?(status.connected?'事件流已连接':'事件流未连接'):'未启用：需配置 PMP_BASE_URL 与 PMP_MONITOR_ENABLED');
    notes.push('快照 '+(status.snapshot==='ok'?'可用':status.snapshot==='unavailable'?'不可用':'未知'));
    notes.push('房间 '+number(rooms.length));
    if(canManageRooms())notes.push('可管理房间 '+number(managed.length));
    if(!data.unrestricted)notes.push('仅显示自己或协作实例的房间');
    if(status.lastError)notes.push(status.lastError);
    if(managedError)notes.push('管理接口不可用：'+managedError);
    box.textContent=notes.join(' · ');
    box.className='callout'+(status.lastError||managedError?' error':'');
    body.innerHTML=rooms.map(function(room){
      const managed=room.managed,chart=managed?.chart||null,chartId=chart?.id??room.chartId??null,chartName=chart?.name||room.chartName||null;
      const count=managed?(managed.users||[]).length:room.playerCount,max=managed?.capacity||room.maxUsers,players=count===null||count===undefined?'—':number(count)+(max?' / '+number(max):'');
      const kind=managed?(managed.hosted?'长期托管房':'预约白名单房'):'普通房间',mode=managed?.hosted?(managed.chart_mode==='POOL_RANDOM'?' · 谱池随机':' · 房主选谱')+(managed.allowed_user_ids?.length?' · 白名单':' · 公开加入'):'';
      const instanceId=room.instanceId||managed?.instanceId||null,host=managed?.host_id??room.hostId??null;
      const actions=managed&&canManageRooms()?'<div class="row-actions">'+(managed.hosted?'<button class="small" data-action="edit-room" data-room="'+esc(room.id)+'">设置</button>':'')+'<button class="small ghost" data-action="room-chat" data-room="'+esc(room.id)+'">公告</button><button class="small ghost danger" data-action="disband-room" data-room="'+esc(room.id)+'">解散</button></div>':'<span class="muted">—</span>';
      return '<tr><td><div class="mono">'+esc(room.id)+'</div><div class="chart-sub">'+kind+mode+'</div></td><td><div class="chart-name">'+esc(chartName||(chartId===null?'（未选谱面）':'#'+chartId))+'</div><div class="chart-sub">'+(chartId===null?'':'#'+chartId)+'</div></td><td>'+esc(roomStateLabel(managed?.state||room.state))+(room.locked?' · 锁定':'')+'</td><td>'+players+'</td><td>'+(host===null?'<span class="muted">待接管</span>':'<span class="mono">#'+host+'</span>')+'</td><td>'+(instanceId?'<span class="badge">'+esc(instanceId)+'</span>':'<span class="muted">未归属</span>')+'</td><td>'+actions+'</td></tr>'
    }).join('')||emptyRow(7,'当前没有房间','可以创建长期托管房或一次性预约白名单房。');
    $('#createHostedRoom').hidden=!canManageRooms();$('#createReservedRoom').hidden=!canManageRooms();
  }catch(error){
    box.textContent='房间列表加载失败：'+(error&&error.message?error.message:String(error));
    box.className='callout error';
  }
  if(state.view==='rooms')roomRefreshTimer=setTimeout(function(){renderRooms(false)},2500)
}
$('#roomsReload').onclick=function(){task(this,function(){return renderRooms(true)})};
function parseRoomIds(value,allowEmpty=false){const parts=String(value||'').split(/[\s,，;；]+/).filter(Boolean);if(!parts.length&&allowEmpty)return [];const ids=[...new Set(parts.map(Number))];if(!parts.length||parts.some(v=>!/^\d+$/.test(v))||ids.some(id=>!Number.isSafeInteger(id)||id<=0||id>2147483647))throw new Error('请填写有效的 Phira UID（正整数）');return ids}
function chartInput(required){const raw=$('#roomChartId').value.trim();if(!raw){if(required)throw new Error('预约房必须选择谱面');return null}const id=Number(raw),local=state.charts.find(chart=>chart.id===id),name=$('#roomChartName').value.trim()||local?.name||'';if(!Number.isSafeInteger(id)||id===0)throw new Error('谱面 ID 必须是非零整数');if(!name)throw new Error('请填写谱面名称');return {id,name}}
function parseRoomPool(){const rows=$('#roomChartPool').value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean),seen=new Set(),charts=[];for(const row of rows){const parts=row.split('|'),id=Number(parts.shift()?.trim()),local=state.charts.find(chart=>chart.id===id),name=parts.join('|').trim()||local?.name||'';if(!Number.isSafeInteger(id)||id===0||!name)throw new Error('谱池每行必须是“非零谱面ID | 谱面名称”');if(!seen.has(id)){seen.add(id);charts.push({id,name})}}return charts}
function syncRoomForm(){const hosted=$('#roomKind').value==='hosted',pool=hosted&&$('#roomChartMode').value==='POOL_RANDOM';$$('[data-room-hosted]').forEach(el=>el.hidden=!hosted);$('#roomPoolField').hidden=!pool;$('#roomExpiryField').hidden=hosted;$('#roomWhitelist').required=!hosted;$('#roomChartId').required=!hosted;$('#roomChartName').required=!hosted;$('#roomExpiry').required=!hosted;$('#roomFormHelp').textContent=hosted?(pool?'玩家 UID 可留空；留空表示所有玩家均可进入。谱池至少需要一张谱面。':'玩家 UID 可留空；留空表示所有玩家均可进入。填写白名单时，协议房主必须在白名单内。'):'预约房是一次性白名单房，必须填写玩家 UID；完整成员进入并准备后自动开始。'}
function openRoomForm(kind,roomId=null){if(state.busy||!canManageRooms())return;roomEditId=roomId;const room=roomId?state.managedRooms.find(item=>item.roomid===roomId):null;if(roomId&&!room?.hosted)return;$('#roomKind').value=kind;$('#roomTitle').textContent=room?'托管房设置 · '+room.roomid:kind==='hosted'?'创建托管房':'创建预约白名单房';$('#roomId').value=room?.roomid||'';$('#roomId').disabled=Boolean(room);$('#roomCapacity').value=room?.capacity||4;$('#roomWhitelist').value=(room?.allowed_user_ids||[]).join(', ');$('#roomHostId').value=room?.host_id||'';$('#roomChartMode').value=room?.chart_mode||'HOST_SELECT';$('#roomChartId').value=room?.chart?.id??'';$('#roomChartName').value=room?.chart?.name||'';$('#roomChartPool').value=(room?.chart_pool||[]).map(chart=>chart.id+' | '+chart.name).join('\n');$('#roomExpiry').value=1800;syncRoomForm();$('#roomDialog').showModal()}
$('#createHostedRoom').onclick=()=>openRoomForm('hosted');$('#createReservedRoom').onclick=()=>openRoomForm('reserved');$('#roomChartMode').onchange=syncRoomForm;$('#roomChartId').oninput=()=>{const chart=state.charts.find(item=>item.id===Number($('#roomChartId').value));if(chart)$('#roomChartName').value=chart.name};
$('#roomForm').onsubmit=e=>{e.preventDefault();const hosted=$('#roomKind').value==='hosted';let ids,chart,pool;try{ids=parseRoomIds($('#roomWhitelist').value,hosted);chart=chartInput(!hosted);pool=parseRoomPool()}catch(error){toast(error.message,true);return}const hostRaw=$('#roomHostId').value.trim(),hostId=hostRaw?Number(hostRaw):null;if(hosted&&ids.length&&hostId!==null&&!ids.includes(hostId)){toast('填写白名单时，协议房主必须在白名单内',true);return}const data=hosted?{roomId:$('#roomId').value.trim(),allowedUserIds:ids,maxUsers:Number($('#roomCapacity').value),hostId,chart,chartMode:$('#roomChartMode').value,chartPool:pool}:{roomId:$('#roomId').value.trim(),allowedUserIds:ids,chart,expiresInSeconds:Number($('#roomExpiry').value)};task(e.submitter,async()=>{const path=roomEditId?'/api/admin/rooms/'+encodeURIComponent(roomEditId)+'/hosted':hosted?'/api/admin/rooms/hosted':'/api/admin/rooms/precreate';if(roomEditId)delete data.roomId;const result=await api(path,jsonOptions(roomEditId?'PATCH':'POST',data));$('#roomDialog').close();toast(result.created===false?'相同配置的房间已经存在':roomEditId?'房间设置已保存':'房间已创建');await renderRooms(true)})};
$('#rooms').onclick=e=>{const button=e.target.closest('[data-action]');if(!button||state.busy)return;const roomId=button.dataset.room;if(button.dataset.action==='edit-room')openRoomForm('hosted',roomId);if(button.dataset.action==='room-chat'){$('#roomChatId').value=roomId;$('#roomChatMessage').value='';$('#roomChatTitle').textContent='发送房间公告 · '+roomId;$('#roomChatDialog').showModal()}if(button.dataset.action==='disband-room')task(button,async()=>{await api('/api/admin/rooms/'+encodeURIComponent(roomId)+'/disband',jsonOptions('POST',{}));toast('房间已解散');await renderRooms(true)})};
$('#roomChatForm').onsubmit=e=>{e.preventDefault();const roomId=$('#roomChatId').value,message=$('#roomChatMessage').value.trim();task(e.submitter,async()=>{await api('/api/admin/rooms/'+encodeURIComponent(roomId)+'/chat',jsonOptions('POST',{message}));$('#roomChatDialog').close();toast('公告已发送')})};
function openEdit(id){if(state.busy)return;const c=state.charts.find(c=>c.id===id);if(!c)return;editId=id;$('#editTitle').textContent='编辑谱面 #'+id;const form=$('#editForm');for(const key of ['name','level','difficulty','charter','composer','illustrator','description'])form.elements[key].value=c[key]??'';form.elements.tags.value=(c.tags||[]).join(', ');form.elements.listed.checked=c.listed!==false;$('#editDialog').showModal()}
function openInstance(id=null){if(state.busy)return;const i=state.instances.find(i=>i.id===id);instanceEditId=id;$('#instanceTitle').textContent=i?'实例设置 · '+i.name:'创建服务实例';$('#instanceId').value=i?.id||'';$('#instanceId').disabled=Boolean(i);$('#instanceName').value=i?.name||'';$('#instanceHosts').value=(i?.hosts||[]).join(', ');$('#instanceEnabled').checked=i?i.enabled:true;$('#instanceHosts').closest('label').hidden=state.user?.role!=='admin';$('#instanceVisibility option[value=legacy]').hidden=Boolean(!i||i.visibility);$('#instanceVisibility').value=i?(i.visibility?.mode||'legacy'):'none';$('#instanceViewers').value=(i?.visibility?.userIds||[]).join('\n');$('#instanceListingWarning').hidden=(i?.listingEnabled??state.instances[0]?.listingEnabled)!==false;syncAudience();prepareInstancePolicy(id);$('#instanceDialog').showModal()}
function confirmDelete(title,message,action){if(state.busy)return;$('#confirmTitle').textContent=title;$('#confirmText').textContent=message;$('#confirmInput').value='';$('#confirmAction').disabled=true;confirmCallback=action;$('#confirmDialog').showModal()}
function deleteCharts(ids){if(!ids.length){toast('没有可删除的谱面',true);return}const scopedIds=[...ids],instance=state.instance;const records=state.records.filter(r=>scopedIds.includes(r.chart)).length;const preview=state.charts.filter(c=>scopedIds.includes(c.id)).slice(0,4).map(c=>c.name+' (#'+c.id+')').join('、');confirmDelete('删除 '+scopedIds.length+' 张谱面','实例：「'+currentName()+'」\n将删除 '+scopedIds.length+' 张谱面、对应资源和 '+records+' 条成绩。\n'+preview+(scopedIds.length>4?' 等':'')+'\n此操作不可撤销。',async()=>{if(instance!==state.instance)throw new Error('实例已切换，请重新选择');const result=scopedIds.length===1?await api('/api/admin/charts/'+scopedIds[0],{method:'DELETE'}):await api('/api/admin/charts/batch-delete',jsonOptions('POST',{ids:scopedIds}));if(!result.deletedIds)result.deletedIds=[result.id];$('#confirmDialog').close();state.selected.clear();toast('已删除 '+result.deletedIds.length+' 张谱面、'+result.recordsDeleted+' 条成绩');await refresh()})}
async function downloadChart(id){const response=await fetch('/api/admin/download/'+id+'?instance='+encodeURIComponent(state.instance),{credentials:'same-origin',headers:$('#token').value?{Authorization:'Bearer '+$('#token').value.trim()}:{}});if(!response.ok)throw new Error('下载失败（HTTP '+response.status+'）');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='#'+id+'_'+chartName(id).replace(/[<>:"/\\|?*]/g,'_')+'.pez';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('#navToggle').onclick=()=>{const open=!$('#workspace').classList.contains('nav-open');$('#workspace').classList.toggle('nav-open',open);$('#sidebarScrim').hidden=!open;$('#navToggle').setAttribute('aria-expanded',String(open));if(open)$('#sidebarClose').focus()};$('#sidebarClose').onclick=()=>{closeNavigation();$('#navToggle').focus()};$('#sidebarScrim').onclick=closeNavigation;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#workspace').classList.contains('nav-open')){closeNavigation();$('#navToggle').focus()}});$$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='docs'){$('#docDialog').showModal();closeNavigation()}else showView(b.dataset.view)});$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('[data-close]').forEach(b=>b.onclick=()=>{if(!state.busy)$('#'+b.dataset.close).close()});$$('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(state.busy)e.preventDefault()}));$('#connectionButton').onclick=()=>{showView('settings');$('#token').focus()};$('#reload').onclick=e=>task(e.currentTarget,refresh);$('#instanceSelect').onchange=e=>task(null,()=>switchInstance(e.target.value));
for(const id of ['chartSearch','tagFilter','visibilityFilter','chartSort'])$('#'+id).addEventListener(id==='chartSearch'?'input':'change',()=>{state.chartPage=1;renderCharts()});for(const id of ['recordSearch','recordChart','recordSort'])$('#'+id).addEventListener(id==='recordSearch'?'input':'change',()=>{state.recordPage=1;renderRecords()});
for(const type of ['chart','record'])for(const direction of ['Prev','Next'])$('#'+type+direction).onclick=()=>{state[type+'Page']+=direction==='Prev'?-1:1;type==='chart'?renderCharts():renderRecords()};
$('#charts').onchange=e=>{if(!e.target.matches('.chart-check'))return;const id=Number(e.target.value);e.target.checked?state.selected.add(id):state.selected.delete(id);renderCharts()};$('#chartHeaderCheck').onchange=e=>{const page=filteredCharts().slice((state.chartPage-1)*20,state.chartPage*20);page.forEach(c=>e.target.checked?state.selected.add(c.id):state.selected.delete(c.id));renderCharts()};$('#selectFiltered').onclick=()=>{filteredCharts().forEach(c=>state.selected.add(c.id));renderCharts()};$('#clearSelection').onclick=()=>{state.selected.clear();renderCharts()};$('#deleteSelected').onclick=()=>deleteCharts([...state.selected]);$('#deleteByTag').onclick=()=>{const tag=$('#deleteTag').value;if(!tag){toast('请先选择标签',true);return}deleteCharts(state.charts.filter(c=>(c.tags||[]).includes(tag)).map(c=>c.id))};$('#deleteAll').onclick=()=>deleteCharts(state.charts.map(c=>c.id));
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||state.busy)return;const id=Number(b.dataset.id),action=b.dataset.action;if(action==='edit')openEdit(id);if(action==='delete')deleteCharts([id]);if(action==='visibility')task(b,async()=>{const c=state.charts.find(c=>c.id===id);await api('/api/admin/charts/'+id,jsonOptions('PATCH',{listed:c.listed===false}));toast(c.listed===false?'谱面已设为在线显示':'谱面已隐藏');await refresh()});if(action==='download')task(b,()=>downloadChart(id));if(action==='preview')openPreview(id);if(action==='delete-record')confirmDelete('删除成绩 #'+id,'实例：「'+currentName()+'」\n此成绩将永久删除，无法撤销。',async()=>{await api('/api/admin/records/'+id,{method:'DELETE'});$('#confirmDialog').close();toast('成绩已删除');await refresh()});if(action==='switch-instance')task(b,()=>switchInstance(b.dataset.instance));if(action==='edit-instance')openInstance(b.dataset.instance);if(action==='delete-instance'){const i=state.instances.find(i=>i.id===b.dataset.instance);confirmDelete('删除实例「'+i.name+'」','将永久删除该实例及其 '+i.chartCount+' 张谱面、'+i.recordCount+' 条成绩和资源。',async()=>{await api('/api/admin/instances/'+encodeURIComponent(i.id),{method:'DELETE'});$('#confirmDialog').close();if(state.instance===i.id){state.instance='default';resetFilters()}toast('实例已删除');await refresh()})}});
$('#confirmInput').oninput=()=>$('#confirmAction').disabled=$('#confirmInput').value.trim()!=='删除';$('#confirmAction').onclick=e=>task(e.currentTarget,async()=>{if($('#confirmInput').value.trim()==='删除'&&confirmCallback)await confirmCallback()});
$('#editForm').onsubmit=e=>{e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form));data.difficulty=Number(data.difficulty);data.tags=tags(data.tags);data.listed=form.elements.listed.checked;if(!capability('chart.tags'))delete data.tags;if(!capability(data.listed?'chart.publish':'chart.hide'))delete data.listed;task(e.submitter,async()=>{await api('/api/admin/charts/'+editId,jsonOptions('PATCH',data));$('#editDialog').close();toast('谱面信息已保存');await refresh()})};
$('#batchTags').onclick=()=>{if(state.busy)return;$('#tagsScope').textContent='将修改「'+currentName()+'」中选中的 '+state.selected.size+' 张谱面。';$('#tagsDialog').showModal()};$('#tagsForm').onsubmit=e=>{e.preventDefault();const mode=$('#tagMode').value,values=tags($('#changeTags').value);if(mode!=='replace'&&!values.length){toast('请输入至少一个标签',true);return}const ids=[...state.selected];task(e.submitter,async()=>{const result=await api('/api/admin/charts/batch-tags',jsonOptions('POST',{ids,tags:values,mode}));$('#tagsDialog').close();toast('已更新 '+result.updated.length+' 张谱面的标签');await refresh()})};
$('#addRecord').onclick=()=>{if(!state.charts.length){toast('请先上传谱面',true);return}$('#recordDialog').showModal()};$('#recordForm').onsubmit=e=>{e.preventDefault();const form=e.target,f=new FormData(form),data={};for(const key of ['player','chart','score','accuracy','perfect','good','bad','miss','maxCombo'])data[key]=Number(f.get(key)||0);data.accuracy/=100;data.fullCombo=form.elements.fullCombo.checked;task(e.submitter,async()=>{await api('/api/admin/records',jsonOptions('POST',data));$('#recordDialog').close();form.reset();toast('本地成绩已保存');await refresh()})};
$('#createInstance').onclick=()=>openInstance();$('#instanceForm').onsubmit=e=>{e.preventDefault();const data={name:$('#instanceName').value.trim(),hosts:tags($('#instanceHosts').value),enabled:$('#instanceEnabled').checked};const mode=$('#instanceVisibility').value;if(mode!=='legacy'){const raw=$('#instanceViewers').value.trim();const parts=raw?raw.split(/[\s,，;；]+/).filter(Boolean):[];const userIds=[...new Set(parts.map(Number))];if(mode==='users'&&(!parts.length||parts.some(v=>!/^\d+$/.test(v))||userIds.length>1000||userIds.some(id=>!Number.isSafeInteger(id)||id<=0||id>2147483647))){toast('请填写 1–1000 个有效的 Phira UID（正整数）',true);return}data.visibility={mode,userIds:mode==='users'?userIds:[]}}if(state.user?.role!=='admin')delete data.hosts;if(instanceEditId){if($('#instanceName').disabled)delete data.name;if($('#instanceVisibility').disabled)delete data.visibility;if($('#instanceEnabled').disabled)delete data.enabled}if(!instanceEditId)data.id=$('#instanceId').value.trim();task(e.submitter,async()=>{const result=await api('/api/admin/instances'+(instanceEditId?'/'+encodeURIComponent(instanceEditId):''),jsonOptions(instanceEditId?'PATCH':'POST',data));$('#instanceDialog').close();if(!instanceEditId){state.instance=result.id;resetFilters()}toast(instanceEditId?'实例设置已保存':'实例已创建');await refresh()})};
function fileChanged(){const file=$('#packageInput').files[0];$('#fileName').textContent=file?file.name+' · '+(file.size/1024/1024).toFixed(2)+' MB':'';$('#packageInput').setCustomValidity(file&&!/\.(pez|zip)$/i.test(file.name)?'请选择 .pez 或 .zip 谱面包':'')}
$('#packageInput').onchange=fileChanged;$('#dropzone').addEventListener('dragover',e=>{e.preventDefault();if(!state.busy)e.currentTarget.classList.add('dragover')});$('#dropzone').addEventListener('dragleave',e=>e.currentTarget.classList.remove('dragover'));$('#dropzone').addEventListener('drop',e=>{e.preventDefault();e.currentTarget.classList.remove('dragover');if(state.busy)return;if(e.dataTransfer.files.length!==1){toast('每次请选择一个谱面包或合集 ZIP',true);return}$('#packageInput').files=e.dataTransfer.files;fileChanged()});
$('#chartForm').onsubmit=e=>{e.preventDefault();const form=e.target,f=new FormData(form);for(const [key,value] of [...f.entries()])if(typeof value==='string'&&!value.trim())f.delete(key);task(e.submitter,async()=>{$('#uploadProgress').hidden=false;$('#uploadStatus').textContent='上传并解析中，请稍候…';$('#uploadResult').hidden=true;const controls=Array.from(form.elements);controls.forEach(el=>el.disabled=true);try{const result=await api('/api/admin/charts',{method:'POST',body:f});form.reset();fileChanged();const box=$('#uploadResult');box.className='callout';box.replaceChildren();const summary=document.createElement('strong');summary.textContent=result.collection?'合集导入完成：新增 '+result.created.length+' 张，跳过 '+result.skipped.length+' 个文件':'「'+result.name+'」上传成功';box.append(summary);if(result.collection&&result.skipped.length){const ul=document.createElement('ul');result.skipped.forEach(item=>{const li=document.createElement('li');li.textContent=typeof item==='string'?item:(item.file||item.filename||item.name||'文件')+'：'+(item.reason||item.error||'已跳过');ul.append(li)});box.append(ul)}box.hidden=false;toast(summary.textContent)}catch(error){$('#uploadResult').textContent='上传未完成：'+error.message;$('#uploadResult').className='callout error';$('#uploadResult').hidden=false;throw error}finally{controls.forEach(el=>el.disabled=false);$('#uploadProgress').hidden=true;$('#uploadStatus').textContent=''}await refresh()})};
$('#connectForm').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await refresh();const token=$('#token').value.trim();storage.set('localStorage',TOKEN_KEY,$('#rememberToken').checked?token:'');storage.set('sessionStorage',TOKEN_KEY,$('#rememberToken').checked?'':token);toast('已连接到「'+currentName()+'」');showView('charts')})};$('#forgetToken').onclick=()=>{if(state.busy)return;storage.set('localStorage',TOKEN_KEY,'');storage.set('sessionStorage',TOKEN_KEY,'');$('#token').value='';$('#rememberToken').checked=false;state.instances=[];state.charts=[];state.records=[];state.selected.clear();$('#loadError').hidden=true;$('#lastUpdated').textContent='等待连接';setConnected(false);render();toast('已清除当前浏览器的连接凭据')};

function renderAccount(){if(!canReview()){$('#reviewDialog').close();$('#reviewApplication').replaceChildren();$('#reviewHistory').replaceChildren();$('#reviewForm').reset();reviewUserId=null}const user=state.user,admin=user?.role==='admin',pending=awaitingApproval(),staff=canReview()||canManageInstances();$('#usersNav').hidden=!canUsers();$('#applicationNav').hidden=!user||admin;$$('[data-view]').forEach(b=>{if(['users','application'].includes(b.dataset.view))return;const denied=b.dataset.view==='rooms'&&!capability('monitor.view')||b.dataset.view==='audit'&&!capability('audit.read');b.hidden=denied||Boolean(pending)&&!['settings','docs'].includes(b.dataset.view)});$('#accountName').textContent=user?(user.username+' · '+levelName(user)):'';$('#accountQuota').textContent=user?(pending?statusLabel(user.approvalStatus):admin?'可管理全部用户与实例':('自己的实例 '+state.instances.filter(i=>i.ownerId===user.id).length+' / '+user.instanceLimit)):'';$('#accountDetails').textContent=user?'当前账号：'+user.username+'。密码修改后，需要重新登录。':'';$('#passwordForm').hidden=user?.id===0;$('#uploadInstance').textContent=state.instances.length?currentName():'请先创建实例'}

$('#userSearch').oninput=renderUsers;$('#approvalFilter').onchange=renderUsers;

$('#showLogin').onclick=()=>{$('#loginForm').hidden=false;$('#registerForm').hidden=true;$('#authError').hidden=true;$('#showLogin').className='primary';$('#showRegister').className='ghost'};
$('#showRegister').onclick=()=>{$('#loginForm').hidden=true;$('#registerForm').hidden=false;$('#authError').hidden=true;$('#showLogin').className='ghost';$('#showRegister').className='primary'};
function clearSession(){reviewUserId=null;permissionsUserId=null;$$('dialog').forEach(d=>d.close());for(const id of ['editForm','recordForm','chartForm','instanceForm','applicationForm','reviewForm','permissionsForm'])$('#'+id).reset();fileChanged();resetFilters();state.user=null;clearPolicyCache();state.csrf='';state.instances=[];state.charts=[];state.records=[];state.users=[];state.selected.clear();$('#token').value='';storage.set('localStorage',TOKEN_KEY,'');storage.set('sessionStorage',TOKEN_KEY,'');setConnected(false);$('#workspace').hidden=true;$('#authGate').hidden=false;$('#passwordForm').reset();render()}
async function enterSession(session){state.user=session.user;state.csrf=session.csrf;$('#token').value='';storage.set('localStorage',TOKEN_KEY,'');storage.set('sessionStorage',TOKEN_KEY,'');$('#authGate').hidden=true;$('#workspace').hidden=false;await refresh();const view=awaitingApproval()?'application':state.instances.length?'charts':'instances';showView(titles[initialView]?initialView:view);if(initialView==='docs')$('#docDialog').showModal()}
for(const [id,action] of [['loginForm','login'],['registerForm','register'],['setupForm','setup']])$('#'+id).onsubmit=e=>{e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form));if(data.confirmPassword!==undefined&&data.password!==data.confirmPassword){$('#authError').textContent='两次输入的密码不一致';$('#authError').hidden=false;return}delete data.confirmPassword;if(action==='register'){data.application=readApplication(form);for(const key of ['reason','useType','organization','socialAccount','notes'])delete data[key]}task(e.submitter,async()=>{try{$('#authError').hidden=true;const session=await api('/api/admin/auth/'+action,jsonOptions('POST',data));form.reset();await enterSession(session);toast(action==='login'?'已登录':action==='setup'?'超级管理员已创建':'注册申请已提交，请等待审核')}catch(error){$('#authError').textContent=error.message;$('#authError').hidden=false;throw error}})};
$('#logoutButton').onclick=e=>task(e.currentTarget,async()=>{await api('/api/admin/auth/logout',jsonOptions('POST',{}));clearSession();toast('已退出登录')});
$('#passwordForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(data.password!==data.confirmPassword){toast('两次输入的新密码不一致',true);return}delete data.confirmPassword;task(e.submitter,async()=>{await api('/api/admin/auth/password',jsonOptions('POST',data));clearSession();toast('密码已修改，请重新登录')})};

function readApplication(form){const data=new FormData(form);return Object.fromEntries(['reason','useType','organization','socialAccount','notes'].map(key=>[key,String(data.get(key)||'')]))}
function groupField(form){const group=form.elements.useType.value==='group';form.querySelector('[data-organization]').hidden=!group;form.elements.organization.required=group}
for(const id of ['registerForm','applicationForm'])$('#'+id).elements.useType.onchange=()=>groupField($('#'+id));
function renderApplication(){const user=state.user;if(!user)return;const form=$('#applicationForm');for(const key of ['reason','useType','organization','socialAccount','notes'])form.elements[key].value=user.application?.[key]|| (key==='useType'?'personal':'');groupField(form);const approved=user.approvalStatus==='approved';Array.from(form.elements).forEach(el=>el.disabled=approved);$('#resubmitApplication').hidden=approved;$('#applicationStatus').className='callout'+(user.approvalStatus==='rejected'?' error':'');$('#applicationStatus').textContent=approved?'申请已通过，可以使用实例管理功能。':user.approvalStatus==='rejected'?'申请未通过。审核意见：'+(user.reviewNote||'请补充资料后重新提交。'):'申请正在等待审核，通过前不能创建或管理实例。你可以补充下方资料并重新提交。';$('#applicationReviewedAt').textContent=user.reviewedAt?'审核于 '+formatTime(user.reviewedAt):''}
$('#applicationForm').onsubmit=e=>{e.preventDefault();const application=readApplication(e.target);task(e.submitter,async()=>{const result=await api('/api/admin/auth/application',jsonOptions('POST',{application}));state.user=result.user;toast('申请资料已更新，等待审核');await refresh()})};
async function openReview(id){const user=state.users.find(u=>u.id===id);if(!user)return;reviewUserId=id;reviewRevision=user.applicationRevision;$('#reviewTitle').textContent='注册申请 · '+user.username;const a=user.application||{},items=[['审核状态',statusLabel(user.approvalStatus)],['注册原因',a.reason||'升级前账号，未填写申请资料'],['用途类型',a.useType==='group'?'团体用途':'个人用途'],['团体名称',a.organization||'—'],['社交账号',a.socialAccount||'—'],['补充说明',a.notes||'—'],['上次审核意见',user.reviewNote||'—']];$('#reviewApplication').innerHTML='<dl>'+items.map(([key,value])=>'<dt>'+esc(key)+'</dt><dd>'+esc(value)+'</dd>').join('')+'</dl>';$('#reviewForm').hidden=user.approvalStatus!=='pending'||user.disabled||user.id===state.user.id;for(const option of $('#reviewDecision').options)option.disabled=!state.user.globalCapabilities.includes(option.value==='rejected'?'review.reject':'review.approve');$('#reviewNote').value='';$('#reviewDecision').value='approved';$('#reviewNote').required=false;const history=await api('/api/admin/users/'+id+'/history');$('#reviewHistory').innerHTML=history.map(item=>'<p>'+esc(formatTime(item.created))+' · '+esc({approved:'审核通过',rejected:'审核拒绝',resubmit:'重新提交',permissions:'权限调整'}[item.action]||item.action)+' · 操作者 #'+item.actorId+'<br>'+esc(item.note)+'</p>').join('')||'暂无处理记录';$('#reviewDialog').showModal()}
$('#reviewDecision').onchange=()=>$('#reviewNote').required=$('#reviewDecision').value==='rejected';
$('#reviewForm').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('/api/admin/users/'+reviewUserId+'/review',jsonOptions('POST',{revision:reviewRevision,decision:$('#reviewDecision').value,note:$('#reviewNote').value.trim()}));$('#reviewDialog').close();toast('审核结果已保存');await refresh()})};


${policyClient()}
${previewClient()}
var DOC_META={user:{title:'用户接入指南',intro:'Phira 客户端连接与使用说明。'},api:{title:'API 文档',intro:'接口、接入方式与错误码。'}};
var docPdfId='';
var DOC_BT=String.fromCharCode(96),DOC_FENCE=DOC_BT+DOC_BT+DOC_BT;
function docInline(value){var text=esc(value);text=text.replace(new RegExp(DOC_BT+'([^'+DOC_BT+']+)'+DOC_BT,'g'),'<code>$1</code>');text=text.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');text=text.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,function(whole,label,url){return '<a href="'+url+'"'+(/^https?:\/\//i.test(url)?' target="_blank" rel="noopener"':'')+'>'+label+'</a>'});return text}
function docRow(line){return line.replace(/^\s*\|/,'').replace(/\|\s*$/,'').split('|').map(cell=>docInline(cell.trim()))}
function renderMarkdown(source){source=String(source||'').replace(/\r\n?/g,'\n');var lines=source.split('\n'),out=[],i=0;while(i<lines.length){var trim=lines[i].trim();if(!trim){i++;continue}if(trim.indexOf(DOC_FENCE)===0){var code=[];i++;while(i<lines.length&&lines[i].trim().indexOf(DOC_FENCE)!==0){code.push(lines[i]);i++}i++;out.push('<pre><code>'+esc(code.join('\n'))+'</code></pre>');continue}if(i+1<lines.length&&lines[i].indexOf('|')>=0&&/^\s*\|?[\s:|-]+\|?\s*$/.test(lines[i+1])&&lines[i+1].indexOf('-')>=0){var rows=[docRow(lines[i])];i+=2;while(i<lines.length&&lines[i].trim().indexOf('|')>=0){rows.push(docRow(lines[i]));i++}var head=rows.shift()||[];out.push('<div class="doc-table-scroll"><table><thead><tr>'+head.map(cell=>'<th>'+cell+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(cell=>'<td>'+cell+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>');continue}var heading=/^(#{1,6})\s+(.*)$/.exec(trim);if(heading){var level=heading[1].length;out.push('<h'+level+'>'+docInline(heading[2])+'</h'+level+'>');i++;continue}if(/^\s*([-*_])\s*\1\s*\1(?:\s*\1)*\s*$/.test(trim)){out.push('<hr>');i++;continue}if(trim.indexOf('>')===0){var quote=[];while(i<lines.length&&(lines[i].trim().indexOf('>')===0||!lines[i].trim())){if(lines[i].trim().indexOf('>')===0)quote.push(lines[i].replace(/^\s*>\s?/,''));else quote.push('');i++}out.push('<blockquote>'+renderMarkdown(quote.join('\n'))+'</blockquote>');continue}var bullet=/^\s*([-*+])\s+(.*)$/.exec(trim),number=/^\s*\d+\.\s+(.*)$/.exec(trim);if(bullet||number){var ordered=Boolean(number);out.push(ordered?'<ol>':'<ul>');while(i<lines.length){var item=bullet=/^\s*([-*+])\s+(.*)$/.exec(lines[i].trim()),itemNum=/^\s*\d+\.\s+(.*)$/.exec(lines[i].trim());if(!(bullet||itemNum))break;var content=(bullet?bullet[2]:itemNum[1]);i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6})\s|^\s*[-*+]\s|^\s*\d+\.\s|^\s*>\s?/.test(lines[i])&&lines[i].indexOf('|')<0&&lines[i].trim().indexOf(DOC_FENCE)!==0){content+=' '+lines[i].trim();i++}out.push('<li>'+docInline(content)+'</li>')}out.push(ordered?'</ol>':'</ul>');continue}var paragraph=[];while(i<lines.length&&lines[i].trim()&&!/^(#{1,6})\s|^\s*[-*+]\s|^\s*\d+\.\s|^\s*>\s?/.test(lines[i])&&lines[i].trim().indexOf(DOC_FENCE)!==0&&!(lines[i].indexOf('|')>=0&&i+1<lines.length&&/^\s*\|?[\s:|-]+\|?\s*$/.test(lines[i+1])&&lines[i+1].indexOf('-')>=0)){paragraph.push(lines[i]);i++}out.push('<p>'+paragraph.map(line=>docInline(line)).join('<br>')+'</p>')}return out.join('\n')}
var docReturnView='charts';
function openDocument(id){if(!DOC_META[id])return;docPdfId=id;var dialog=$('#docDialog');if(dialog&&dialog.open)dialog.close();docReturnView=state.view==='docs'?'charts':state.view;var meta=DOC_META[id];$('#docHeading').textContent=meta.title;$('#docIntro').textContent=meta.intro;var status=$('#docStatus'),loading=$('#docLoading'),content=$('#docContent');status.hidden=true;status.className='callout';loading.hidden=false;content.hidden=true;content.innerHTML='';task(null,async()=>{try{var doc=await api('/api/admin/docs/'+id);content.innerHTML=renderMarkdown(doc.content||'');loading.hidden=true;content.hidden=false}catch(error){loading.hidden=true;content.hidden=true;status.textContent=error.message||'文档加载失败';status.className='callout error';status.hidden=false}finally{showView('docs')}})}
$('#docBack').onclick=()=>showView(docReturnView==='docs'?'charts':docReturnView);
async function printDocument(){if(!DOC_META[docPdfId])return;var response=await fetch(scopedPath('/api/admin/docs/'+docPdfId+'/print'),{credentials:'same-origin',cache:'no-store',headers:$('#token').value.trim()?{Authorization:'Bearer '+$('#token').value.trim()}:{}});if(!response.ok){var message='打印视图加载失败（HTTP '+response.status+'）';try{var detail=await response.json();if(detail&&detail.error)message=detail.error}catch(error){}throw new Error(message)}var source=await response.text(),frame=document.createElement('iframe');frame.setAttribute('aria-hidden','true');frame.style.cssText='position:fixed;left:-10000px;top:0;width:1024px;height:1414px;border:0';frame.addEventListener('load',function(){var view=frame.contentWindow;if(!view){frame.remove();toast('无法打开打印视图',true);return}var cleanup=function(){frame.remove()};view.addEventListener('afterprint',cleanup,{once:true});setTimeout(cleanup,60000);view.focus();setTimeout(function(){view.print()},50)},{once:true});document.body.append(frame);frame.srcdoc=source}
$('#docPrint').onclick=e=>task(e.currentTarget,printDocument);
$$('.doc-option').forEach(option=>option.onclick=()=>openDocument(option.dataset.doc));
(function(){var connection=$('#connectionButton');if(!connection)return;var button=document.createElement('button');button.className='ghost';button.id='docButton';button.type='button';button.title='打开使用文档';button.textContent='使用文档';connection.parentNode.insertBefore(button,connection);button.onclick=()=>{if(!state.busy)$('#docDialog').showModal()}})();
showView(location.hash.slice(1)||'charts');render();
task(null,async()=>{const status=await api('/api/admin/auth/status');$('#setupDetails').hidden=!status.setupRequired;try{const session=await api('/api/admin/auth/me');await enterSession(session)}catch(error){if(!state.user){$('#workspace').hidden=true;$('#authGate').hidden=false}else throw error}});

`;
}
